.Dd June 2, 2024
.Dt RVN-AUDIT 8
.Os
.Sh NAME
.Nm "rvn audit"
.Nd lists active cybersecurity vulnerabilities
.Sh SYNOPSIS
Not yet implemented.
.Sh SEE ALSO
.Xr rvn-keywords 5 ,
.Xr rvn-lua-scripts 5 ,
.Xr rvn-repository 5 ,
.Xr rvn-scripts 5 ,
.Xr rvn-triggers 5 ,
.Xr rvn.conf 5 ,
.Xr rvn 8 ,
.Xr rvn-alias 8 ,
.Xr rvn-annotate 8 ,
.Xr rvn-autoremove 8 ,
.Xr rvn-catalog 8 ,
.Xr rvn-check 8 ,
.Xr rvn-clean 8 ,
.Xr rvn-config 8 ,
.Xr rvn-create 8 ,
.Xr rvn-fetch 8 ,
.Xr rvn-genrepo 8 ,
.Xr rvn-info 8 ,
.Xr rvn-install 8 ,
.Xr rvn-query 8 ,
.Xr rvn-remove 8 ,
.Xr rvn-rquery 8 ,
.Xr rvn-search 8 ,
.Xr rvn-shell 8 ,
.Xr rvn-shlib 8 ,
.Xr rvn-stats 8 ,
.Xr rvn-upgrade 8 ,
.Xr rvn-version 8 ,
.Xr rvn-which 8
