.Dd May 13, 2024
.Dt RVN-INFO 8
.Os
.Sh NAME
.Nm "rvn info"
.Nd display information for packages
.Sh SYNOPSIS
.Nm
.Ar pkg-name
.Nm
.Fl a
.Nm
.Op Fl ABbMDdefIjpqrsNSV
.Op Fl L | Fl l
.Op Fl Cgix
.Ar pkg-name
.Nm
.Op Fl ABbMDdfIjLlpqRsNSV
.Op Fl L | Fl l | Fl X
.Fl F Ar pkg-file
.Pp
.Nm
.Ar pkg-name
.Nm
.Cm --all
.Nm
.Op Cm --{annotations,required-shlibs,provided-shlibs}
.Op Cm --{pkg-message,description,dependencies,exists}
.Op Cm --{full,comment,adjacent-shlibs,prefix}
.Op Cm --{quiet,required-by,size,namebase,subpackage,variant}
.Op Cm --list-digests | --list-files
.Op Cm --{case-sensitive,glob,case-insensitive,regex}
.Ar pkg-name
.Nm
.Op Cm --{annotations,required-shlibs,provided-shlibs}
.Op Cm --{pkg-message,description,dependencies,full}
.Op Cm --{comment,adjacent-shlibs,prefix}
.Op Cm --{quiet,raw,size,namebase,subpackage,variant}
.Op Cm --list-digests | --list-files | --list-extended
.Op Cm --{case-sensitive,glob,case-insensitive,regex}
.Cm --file Ar pkg-file
.Sh DESCRIPTION
.Nm
is used for displaying information for packages.
.Sh OPTIONS
The following options are supported by
.Nm :
.Bl -tag -width origin
.It Fl A , Cm --annotations
Display any annotations added to the package.
.It Fl a , Cm --all
Display all installed packages.
.It Fl B , Cm --required-shlibs
Display all shared libraries used by
.Ar pkg-name .
.It Fl b , Cm --provided-shlibs
Display all shared libraries provided by
.Ar pkg-name .
.It Fl C , Cm --case-sensitive
Make the standard or the regular expression
.Fl ( x )
matching against
.Ar pkg-name
case sensitive.
.It Fl D , Cm --description
Show the long description for matching packages.
.It Fl d , Cm --dependencies
Display the list of packages on which
.Ar pkg-name
depends.
.It Fl e , Cm --exists
If
.Ar pkg-name
is installed and registered in the database, return 0, otherwise return 1.
Useful for checking whether the package is installed.
.It Fl F Ar pkg-file , Cm --file Ar pkg-file
Displays information from the package archive
.Ar pkg-file .
.It Fl f , Cm --full
Display full information about the packages matching
.Ar pkg-name .
This is the default.
.It Fl g , Cm --glob
Treat
.Ar pkg-name
as a shell glob pattern.
.It Fl I , Cm --comment
Display the specified packages and their comments.
.It Fl i , Cm --case-insensitive
Make the standard or the regular expression
.Fl ( x )
matching against
.Ar pkg-name
case insensitive.
This is the default, unless modified by setting
.Ev CASE_SENSITIVE_MATCH
to true in
.Pa rvn.conf .
.It Fl j , Cm --adjacent-shlibs
Display all libraries that were present in the stage directory but not
present in this package.
They are likely packaged in a sister subpackage so any missing required shared
library on this list should not cause a notice to be emitted during packaging.
.It Fl L , Cm --list-digests
Display the digests of all files install by
.Ar pkg-name .
It is mutually exclusive with -l and -X options.
.It Fl l , Cm --list-files
Display all files installed by
.Ar pkg-name .
It is mutally exclusive with -L option and -X options
.It Fl M , Cm --pkg-message
Show the pkg-message for matching packages.
.It Fl N , Cm --namebase
Display the namebase (the first part of the package name triplet).
.It Fl p , Cm --prefix
Display the installation prefix for each package matching
.Ar pkg-name .
.It Fl q , Cm --quiet
Be
.Dq quiet .
Prints only the requested information without displaying many hints.
.It Fl R , Cm --raw
Display the full UCL-formatted manifest for the packages matching
.Ar pkg-name .
.It Fl r , Cm --required-by
Display the list of packages which require
.Ar pkg-name .
.It Fl S , Cm --subpackage
Display the subpackage (the secondard part of the package name triplet).
.It Fl s , Cm --size
Display the total size of files installed by
.Ar pkg-name .
.It Fl V , Cm --variant
Display the variant (the third part of the package name triplet).
.It Fl X , Cm --list-extended
Display the long format of all files install by
.Ar pkg-name .
It is mutually exclusive with -l and -L options.
.It Fl x , Cm --regex
Treat
.Ar pkg-name
as a regular expression according to the "modern" or "extended" syntax
of
.Xr re_format 7 .
.El
.Sh ENVIRONMENT
The following environment variables affect the execution of
.Nm .
See
.Xr rvn.conf 5
for further description.
.Bl -tag -width ".Ev NO_DESCRIPTIONS"
.It Ev RVN_DBDIR
.It Ev CASE_SENSITIVE_MATCH
.El
.Sh SEE ALSO
.Xr rvn-keywords 5 ,
.Xr rvn-lua-scripts 5 ,
.Xr rvn-scripts 5 ,
.Xr rvn.conf 5 ,
.Xr rvn 8 ,
.Xr rvn-alias 8 ,
.Xr rvn-catalog 8 ,
.Xr rvn-config 8 ,
.Xr rvn-create 8 ,
.Xr rvn-genrepo 8 ,
.Xr rvn-install 8 ,
.Xr rvn-shell 8 ,
.Xr rvn-shlib 8 ,
.Xr rvn-version 8 ,
.Xr rvn-which 8
