.Dd November 30, 2023
.Dt RVN-SCRIPT 5
.Os
.Sh NAME
.Nm "shell scripts"
.Nd Shell scripts that are run by
.Xr rvn 8
.Sh DESCRIPTION
.Xr rvn 8
runs scripts at distinct phases of package maintenance:
.Bl -tag -width Ds
.It Cm pre-install :
runs script before installing files on the system.
.It Cm post-install :
runs script after installing files on the system.
.It Cm pre-deinstall :
runs script before removing files on the system.
.It Cm post-deinstall :
runs script after removing files on the system.
.El
.Pp
In the case of a package upgrade, the scripts are run in the following order:
.Bl -enum -compact
.It
new pre-install
.It
old pre-deinstall
.It
replace binaries
.It
new post-install
.El
.Sh Environment
The following environment variable are exported to be used by the script:
.Bl -tag -width Ds
.It Ev PKG_NAMEBASE
Represents the namebase of the port that created the package.
.It Ev PKG_SUBPACKAGE
Represents the subpackage of the port variant.
.It Ev PKG_VARIANT
Represents the name of the variant of the port.
.It Ev PKG_PREFIX
.Va PREFIX
defined within the package at build time.
.It Ev PKG_ROOTDIR
represents the root directory where the package will be installed as specified
by the
.Fl r
arguments passed to
.Xr rvn 8 .
.It Ev PKG_MSGFD
Number of a file descriptor to be used to be able to send messages to the user
that will be shown at the end of the
.Xr rvn 8
process.
.It Ev PKG_UPGRADE
Variable existing when the scripts is run in the context of an upgrade
of the package
.El
.Sh SEE ALSO
.Xr rvn-keywords 5 ,
.Xr rvn 8 ,
.Xr rvn-alias 8 ,
.Xr rvn-config 8 ,
.Xr rvn-create 8 ,
.Xr rvn-info 8
