.Dd June 2, 2024
.Dt RVN 8
.Os
.\" ---------------------------------------------------------------------------
.Sh NAME
.Nm rvn
.Nd Ravenports package manager
.\" ---------------------------------------------------------------------------
.Sh SYNOPSIS
.Nm
.Op Fl v
.Op Fl d
.Op Fl l
.Op Fl c Ao chroot path Ac | Fl r Ao root directory Ac
.Op Fl C Ao configuration file Ac
.Op Fl o Ao option=value Ac
.Op Fl R Ao repository configuration directory Ac
.Op Fl 4 | Fl 6
.Ao command Ac Ao Ar command-arguments Ac
.Pp
.Nm
.Op Cm --version
.Op Cm --debug
.Op Cm --list
.Op Cm --status-check
.Op Cm --chroot Ao chroot path Ac | Cm --rootdir Ao root directory Ac
.Op Cm --config Ao configuration file Ac
.Op Cm --option Ao option=value Ac
.Op Cm --repo-conf-dir Ao repository configuration directory Ac
.Op Fl 4 | Fl 6
.Ao command Ac Ao Ar command-arguments Ac
.\" ---------------------------------------------------------------------------
.Sh DESCRIPTION
.Nm rvn
provides an interface for manipulating packages from Ravenports: installing,
adding, inspecting, removing and upgrading packages.
.\" ---------------------------------------------------------------------------
.Sh OPTIONS
The following options are supported by
.Nm :
.Bl -tag -width indent
.It Fl v , Cm --version
Display the current version of
.Nm .
.It Fl d , Cm --debug
Show debug information.
.It Fl l , Cm --list
List all the available command names, and exit without performing any
other action.
The
.Fl v
option takes precedence over
.Fl l
but
.Fl l
will override any other command line arguments.
.It Fl o Ao option=value Ac , Cm --option Ao option=value Ac
Set configuration option for
.Nm
from the command line.
Options that are set from the environment are redefined.
It is permitted to specify this option multiple times.
.It Cm --status-check
Activation status check mode.
.Nm
will run sanity tests.
It first checks for the existence
of the SQLite database as specified by the configuration.
It then attempts to run a simple read-only query to determine the
number of packages installed.
If the query is successful, and at least one package is installed,
.Nm
will exit normally after printing out the number of installed
packages, otherwise an error message will be printed.
The exit status should be a reliable indication of whether a system
is configured to use
.Nm
as its package management system or not.
.Pp
Example usage:
.Bd -literal -offset indent
  if rvn --status-check >/dev/null 2>&1; then
    # rvn functional
  else
    # rvn missing or non-functional
  fi
.Ed
.It Fl c Ao chroot path Ac , Cm --chroot Ao chroot path Ac
.Nm
will chroot in the
.Ao chroot path Ac
environment.
.It Fl r Ao root directory Ac , Cm --rootdir Ao root directory Ac
.Nm
will install all packages within the specified
.Ao root directory Ac .
.It Fl C Ao configuration file Ac , Cm --config Ao configuration file Ac
.Nm
will use the specified file as a configuration file.
.It Fl R Ao repo conf dir Ac , Cm --repo-conf-dir Ao repo conf dir Ac
.Nm
will search the directory for per-repository configuration files.
This overrides any value of
.Ev REPOS_DIR
specified in the main configuration file.
.It Fl 4
.Nm
will be restricted to IPv4 for fetching repository and packages.
.It Fl 6
.Nm
will be restricted to IPv6 for fetching repository and packages.
.El
.\" ---------------------------------------------------------------------------
.Sh COMMANDS
The following commands (or their unambiguous abbreviations) are supported by
.Nm :
.Bl -tag -width autoremove
.It Ic help Ar command
Display usage information of the specified command.
.It Ic alias
Lists the command line aliases
.It Ic annotate
Manipulate installed package annotations
.It Ic audit
lists active cybersecurity vulnerabilities
.It Ic autoremove
Removes orphan packages
.It Ic catalog
Ensures local package catalog is up to date
.It Ic check
Verifies integrity of installed packages
.It Ic clean
Cleans the local cache of downloaded packages
.It Ic config
Displays the value of a configuration option
.It Ic create
Creates software packages for distribution
.It Ic fetch
Fetches packages from a remote repository
.It Ic genrepo
Creates a package repository catalog
.It Ic info
Displays information about installed packages
.It Ic install
Installs packages from remote and local repositories
.It Ic query
Queries installed packages database
.It Ic remove
Removes packages from the database and the system
.It Ic rquery
Queries remote catalog
.It Ic search
Performs search of the package repository catalog
.It Ic shell
Opens a command shell for the local SQLite database
.It Ic shlib
Displays packages that link against a specific library
.It Ic stats
Displays package database statistics
.It Ic version
Displays the currency of installed packages
.It Ic which
Displays which package installed a specific file
.El
.\" ---------------------------------------------------------------------------
.Sh ENVIRONMENT
All configuration options from
.Xr rvn.conf 5
can be passed as environment variables.
.\" ---------------------------------------------------------------------------
.Sh FILES
See
.Xr rvn.conf 5 .
.\" ---------------------------------------------------------------------------
.Sh EXAMPLES
Search for a package:
.Dl % rvn search joe
.Pp
Install a package:
.Dl Installing must specify the unique namebase-variant-subpackage
.D1 triple identifier otherwise it will try installing all matches.
.Pp
.Dl % rvn install joe
.Dl % rvn install joe-single-standard
.Pp
List installed packages:
.Dl % rvn info
.Pp
Upgrade from remote repository:
.Dl % rvn upgrade
.Pp
List non-automatic packages:
.Dl % rvn query -a -e '{auto} eq 0' '{nsv}'
.Pp
List automatic packages:
.Dl % rvn query -a -e '{auto} eq 1' '{nsv}'
.Pp
Delete an installed package:
.Dl % rvn remove -f joe
.Pp
Remove unneeded depencies:
.Dl % rvn autoremove
.Pp
Determine which pack installed a file:
.Dl $ rvn which /raven/bin/joe
.Pp
Check installed packages for checksum mismatches:
.Dl rvn check -a -s
.Pp
Check for missing dependencies:
.Dl rvn check -a -d
.\" ------------------------------------------------------------------------
.Sh SEE ALSO
.Xr rvn-keywords 5 ,
.Xr rvn-lua-scripts 5 ,
.Xr rvn-repository 5 ,
.Xr rvn-scripts 5 ,
.Xr rvn-triggers 5 ,
.Xr rvn.conf 5 ,
.Xr rvn-alias 8 ,
.Xr rvn-annotate 8 ,
.Xr rvn-audit 8 ,
.Xr rvn-autoremove 8 ,
.Xr rvn-catalog 8 ,
.Xr rvn-check 8 ,
.Xr rvn-clean 8 ,
.Xr rvn-config 8 ,
.Xr rvn-create 8 ,
.Xr rvn-fetch 8 ,
.Xr rvn-genrepo 8 ,
.Xr rvn-info 8 ,
.Xr rvn-install 8 ,
.Xr rvn-query 8 ,
.Xr rvn-remove 8 ,
.Xr rvn-rquery 8 ,
.Xr rvn-search 8 ,
.Xr rvn-shell 8 ,
.Xr rvn-shlib 8 ,
.Xr rvn-stats 8 ,
.Xr rvn-upgrade 8 ,
.Xr rvn-version 8 ,
.Xr rvn-which 8
.\" ---------------------------------------------------------------------------
.Sh HISTORY
The pkg command first appeared in
.Fx 9.1 .
The
.Nm
program was implemented in Ada from scratch to work similarly to pkg(8) while
also natively supporting specific Ravenports features such as subpackages
and variants.
.\" ---------------------------------------------------------------------------
.Sh AUTHORS AND CONTRIBUTORS
.An John Marino Aq draco@marino.st
.\" ---------------------------------------------------------------------------
.Sh BUGS
See the issue tracker at
.Em https://github.com/Ravenports/rvn/issues
